channels:
  - conda-forge
  - ome
dependencies:
  - matplotlib=3.3.2
  - scikit-image=0.17.2
  - scipy=1.5.2
  - pip
  # ome: minimal dependencies required to use the Python API
  - omero-py
  # dependencies to use for zarr work
  - imageio=2.6.1
  - pip:
    - ome-zarr
    - dask-image
