channels:
  - conda-forge
  - ome
dependencies:
  - matplotlib
  - scikit-image
  - scipy
  - pip
  # ome: minimal dependencies required to use the Python API
  - omero-py
  # dependencies to use for zarr work
  - dask-image
  - imageio
  - pip:
    - ome-zarr
