# Builds the Sphinx documentation in the specified folder.
# Default is docs/

---
name: sphinx

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      directory_path: ${{ secrets.directory_path }}
      check_link: ${{ secrets.check_link }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Sphinx install
        run: pip install --upgrade sphinx
      - name: Set directory
        run: echo "docs_dir=./docs" >> $GITHUB_ENV
        if: ${{ env.directory_path == '' }}
      - name: Set directory
        if: ${{ env.directory_path != '' }}
        run: |
          echo "docs_dir="${{ env.directory_path }} >> $GITHUB_ENV
      - name: Set check link option
        run: echo "check_link=true" >> $GITHUB_ENV
        if: ${{ env.check_link == '' }}
      - name: Set check link option
        if: ${{ env.check_link != '' }}
        run: |
          echo "check_link=false" >> $GITHUB_ENV
      - name: Build doc
        run: |
          cd $docs_dir
          if [ ! $check_link ]; then
            make clean html linkcheck
          else
            make clean html
          fi 
        