# Builds the Sphinx documentation in the specified folder.
# Default is docs/

---
name: sphinx

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      directory: ${{ secrets.directory_path }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Sphinx install
        run: pip install --upgrade sphinx
      - name: Set directory
        run: ${{ env.directory }} = "./docs"
        if:  ${{ env.directory }} == ''
      - name: Build doc
        working-directory: ${{ env.directory }}
        run: |
          make clean html linkcheck
        