# Builds the Sphinx documentation in the specified folder.
# Default is docs/

---
name: sphinx

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Sphinx install
        run: pip install --upgrade sphinx
      - name: Set directory
        run: |
          echo "::set-env name=DOCS_DIR::${{ ${{ secrets.directory_path }} ".format("./docs")
      - name: Build doc
        working-directory: $DOCS_DIR
        run: |
          make clean html linkcheck
        