# Builds the Sphinx documentation in the specified folder.
# Default is docs/

---
name: sphinx

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      directory_path: ${{ secrets.directory_path }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Sphinx install
        run: pip install --upgrade sphinx
      - name: Set directory
        run: echo "docs_dir=./docs" >> $GITHUB_ENV
        if:  ${{ env.directory_path == '' }}
      - name: Set directory
        if:  ${{ env.directory_path != '' }}
        run: |
          echo ${{ env.directory_path }}
          echo "docs_dir="${{ env.directory_path }} >> $GITHUB_ENV
      - name: Build doc
        run: |
          cd $docs_dir
          make clean html linkcheck
        