# Builds the Sphinx documentation in the specified folder.
# Default is docs/

---
name: sphinx

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      directory_path:
      check_link: true # set to false to remove linkcheck
    steps:
      - uses: actions/checkout@v2
      - name: Set directory
        run: |
          VAR=${{ env.directory_path }}
          echo "docs_dir="${VAR:-./docs} >> $GITHUB_ENV
      - name: Set command
        run: |
          if [ "${{ env.check_link }}" = true ]; then
            echo "docs_command=make clean html linkcheck" >> $GITHUB_ENV
          else
            echo "docs_command=make clean html" >> $GITHUB_ENV
          fi
          
      - name: Build doc
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: ${{ env.docs_dir }}
          build-command: ${{ env.docs_command }}
