# Builds the Sphinx documentation in the specified folder.
# Default is docs/

---
name: sphinx

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      directory_path:
      check_link: true # set to false to remove linkcheck
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Sphinx install
        run: pip install --upgrade sphinx
      - name: Set directory
        run: |
          VAR=${${{ env.directory_path }}:=./docs}
          echo "docs_dir="${VAR} >> $GITHUB_ENV
      - name: Build doc
        run: |
          cd $docs_dir
          make clean html
