# Builds the Sphinx documentation in the specified folder.
# Default is docs/

---
name: sphinx

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      directory_path: ${{ secrets.directory_path }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Sphinx install
        run: pip install --upgrade sphinx
      - name: Set docs directory 
        run: |
          echo ${{ env.directory_path }}
          echo "docs_dir=./docs" >> $GITHUB_ENV 
      - name: Build doc
        working-directory: $docs_dir
        run: |
          make clean html linkcheck
        